/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  admin: {
    ActivityLogs: () => import('#controllers/admin/activity_logs_controller'),
    Articles: () => import('#controllers/admin/articles_controller'),
    Categories: () => import('#controllers/admin/categories_controller'),
    Certifications: () => import('#controllers/admin/certifications_controller'),
    Dashboard: () => import('#controllers/admin/dashboard_controller'),
    Educations: () => import('#controllers/admin/educations_controller'),
    Experiences: () => import('#controllers/admin/experiences_controller'),
    Expertises: () => import('#controllers/admin/expertises_controller'),
    Inboxes: () => import('#controllers/admin/inboxes_controller'),
    Media: () => import('#controllers/admin/media_controller'),
    Philosophies: () => import('#controllers/admin/philosophies_controller'),
    ProjectCategories: () => import('#controllers/admin/project_categories_controller'),
    Projects: () => import('#controllers/admin/projects_controller'),
    Security: () => import('#controllers/admin/security_controller'),
    Services: () => import('#controllers/admin/services_controller'),
    Settings: () => import('#controllers/admin/settings_controller'),
    Tags: () => import('#controllers/admin/tags_controller'),
    TechStacks: () => import('#controllers/admin/tech_stacks_controller'),
    Workflows: () => import('#controllers/admin/workflows_controller'),
  },
  auth: {
    Auth: () => import('#controllers/auth/auth_controller'),
    Passkey: () => import('#controllers/auth/passkey_controller'),
  },
  public: {
    Articles: () => import('#controllers/public/articles_controller'),
    Experiences: () => import('#controllers/public/experiences_controller'),
    Expertises: () => import('#controllers/public/expertises_controller'),
    Inboxes: () => import('#controllers/public/inboxes_controller'),
    Philosophies: () => import('#controllers/public/philosophies_controller'),
    Projects: () => import('#controllers/public/projects_controller'),
    Services: () => import('#controllers/public/services_controller'),
    Settings: () => import('#controllers/public/settings_controller'),
    TechStacks: () => import('#controllers/public/tech_stacks_controller'),
    Workflows: () => import('#controllers/public/workflows_controller'),
  },
}
