/* eslint-disable prettier/prettier */
import type { AdonisEndpoint } from '@tuyau/core/types'
import type { Registry } from './schema.d.ts'
import type { ApiDefinition } from './tree.d.ts'

const placeholder: any = {}

const routes = {
  'drive.local.serve': {
    methods: ["GET","HEAD"],
    pattern: '/uploads/*',
    tokens: [{"old":"/uploads/*","type":0,"val":"uploads","end":""},{"old":"/uploads/*","type":2,"val":"*","end":""}],
    types: placeholder as Registry['drive.local.serve']['types'],
  },
  'event_stream': {
    methods: ["GET","HEAD"],
    pattern: '/__transmit/events',
    tokens: [{"old":"/__transmit/events","type":0,"val":"__transmit","end":""},{"old":"/__transmit/events","type":0,"val":"events","end":""}],
    types: placeholder as Registry['event_stream']['types'],
  },
  'subscribe': {
    methods: ["POST"],
    pattern: '/__transmit/subscribe',
    tokens: [{"old":"/__transmit/subscribe","type":0,"val":"__transmit","end":""},{"old":"/__transmit/subscribe","type":0,"val":"subscribe","end":""}],
    types: placeholder as Registry['subscribe']['types'],
  },
  'unsubscribe': {
    methods: ["POST"],
    pattern: '/__transmit/unsubscribe',
    tokens: [{"old":"/__transmit/unsubscribe","type":0,"val":"__transmit","end":""},{"old":"/__transmit/unsubscribe","type":0,"val":"unsubscribe","end":""}],
    types: placeholder as Registry['unsubscribe']['types'],
  },
  'auth.login': {
    methods: ["POST"],
    pattern: '/api/auth/login',
    tokens: [{"old":"/api/auth/login","type":0,"val":"api","end":""},{"old":"/api/auth/login","type":0,"val":"auth","end":""},{"old":"/api/auth/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['auth.login']['types'],
  },
  'passkey.generate_authentication_options': {
    methods: ["POST"],
    pattern: '/api/auth/passkey/generate-authentication-options',
    tokens: [{"old":"/api/auth/passkey/generate-authentication-options","type":0,"val":"api","end":""},{"old":"/api/auth/passkey/generate-authentication-options","type":0,"val":"auth","end":""},{"old":"/api/auth/passkey/generate-authentication-options","type":0,"val":"passkey","end":""},{"old":"/api/auth/passkey/generate-authentication-options","type":0,"val":"generate-authentication-options","end":""}],
    types: placeholder as Registry['passkey.generate_authentication_options']['types'],
  },
  'passkey.verify_authentication': {
    methods: ["POST"],
    pattern: '/api/auth/passkey/verify-authentication',
    tokens: [{"old":"/api/auth/passkey/verify-authentication","type":0,"val":"api","end":""},{"old":"/api/auth/passkey/verify-authentication","type":0,"val":"auth","end":""},{"old":"/api/auth/passkey/verify-authentication","type":0,"val":"passkey","end":""},{"old":"/api/auth/passkey/verify-authentication","type":0,"val":"verify-authentication","end":""}],
    types: placeholder as Registry['passkey.verify_authentication']['types'],
  },
  'auth.me': {
    methods: ["GET","HEAD"],
    pattern: '/api/auth/me',
    tokens: [{"old":"/api/auth/me","type":0,"val":"api","end":""},{"old":"/api/auth/me","type":0,"val":"auth","end":""},{"old":"/api/auth/me","type":0,"val":"me","end":""}],
    types: placeholder as Registry['auth.me']['types'],
  },
  'auth.logout': {
    methods: ["POST"],
    pattern: '/api/auth/logout',
    tokens: [{"old":"/api/auth/logout","type":0,"val":"api","end":""},{"old":"/api/auth/logout","type":0,"val":"auth","end":""},{"old":"/api/auth/logout","type":0,"val":"logout","end":""}],
    types: placeholder as Registry['auth.logout']['types'],
  },
  'passkey.generate_registration_options': {
    methods: ["POST"],
    pattern: '/api/auth/passkey/generate-registration-options',
    tokens: [{"old":"/api/auth/passkey/generate-registration-options","type":0,"val":"api","end":""},{"old":"/api/auth/passkey/generate-registration-options","type":0,"val":"auth","end":""},{"old":"/api/auth/passkey/generate-registration-options","type":0,"val":"passkey","end":""},{"old":"/api/auth/passkey/generate-registration-options","type":0,"val":"generate-registration-options","end":""}],
    types: placeholder as Registry['passkey.generate_registration_options']['types'],
  },
  'passkey.verify_registration': {
    methods: ["POST"],
    pattern: '/api/auth/passkey/verify-registration',
    tokens: [{"old":"/api/auth/passkey/verify-registration","type":0,"val":"api","end":""},{"old":"/api/auth/passkey/verify-registration","type":0,"val":"auth","end":""},{"old":"/api/auth/passkey/verify-registration","type":0,"val":"passkey","end":""},{"old":"/api/auth/passkey/verify-registration","type":0,"val":"verify-registration","end":""}],
    types: placeholder as Registry['passkey.verify_registration']['types'],
  },
  'admin_dashboard.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/dashboard',
    tokens: [{"old":"/api/admin/dashboard","type":0,"val":"api","end":""},{"old":"/api/admin/dashboard","type":0,"val":"admin","end":""},{"old":"/api/admin/dashboard","type":0,"val":"dashboard","end":""}],
    types: placeholder as Registry['admin_dashboard.index']['types'],
  },
  'admin_projects.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/projects',
    tokens: [{"old":"/api/admin/projects","type":0,"val":"api","end":""},{"old":"/api/admin/projects","type":0,"val":"admin","end":""},{"old":"/api/admin/projects","type":0,"val":"projects","end":""}],
    types: placeholder as Registry['admin_projects.index']['types'],
  },
  'admin_projects.store': {
    methods: ["POST"],
    pattern: '/api/admin/projects',
    tokens: [{"old":"/api/admin/projects","type":0,"val":"api","end":""},{"old":"/api/admin/projects","type":0,"val":"admin","end":""},{"old":"/api/admin/projects","type":0,"val":"projects","end":""}],
    types: placeholder as Registry['admin_projects.store']['types'],
  },
  'admin_projects.reorder': {
    methods: ["POST"],
    pattern: '/api/admin/projects/reorder',
    tokens: [{"old":"/api/admin/projects/reorder","type":0,"val":"api","end":""},{"old":"/api/admin/projects/reorder","type":0,"val":"admin","end":""},{"old":"/api/admin/projects/reorder","type":0,"val":"projects","end":""},{"old":"/api/admin/projects/reorder","type":0,"val":"reorder","end":""}],
    types: placeholder as Registry['admin_projects.reorder']['types'],
  },
  'admin_projects.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/projects/:id',
    tokens: [{"old":"/api/admin/projects/:id","type":0,"val":"api","end":""},{"old":"/api/admin/projects/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/projects/:id","type":0,"val":"projects","end":""},{"old":"/api/admin/projects/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_projects.show']['types'],
  },
  'admin_projects.analytics': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/projects/:id/analytics',
    tokens: [{"old":"/api/admin/projects/:id/analytics","type":0,"val":"api","end":""},{"old":"/api/admin/projects/:id/analytics","type":0,"val":"admin","end":""},{"old":"/api/admin/projects/:id/analytics","type":0,"val":"projects","end":""},{"old":"/api/admin/projects/:id/analytics","type":1,"val":"id","end":""},{"old":"/api/admin/projects/:id/analytics","type":0,"val":"analytics","end":""}],
    types: placeholder as Registry['admin_projects.analytics']['types'],
  },
  'admin_projects.update': {
    methods: ["PUT"],
    pattern: '/api/admin/projects/:id',
    tokens: [{"old":"/api/admin/projects/:id","type":0,"val":"api","end":""},{"old":"/api/admin/projects/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/projects/:id","type":0,"val":"projects","end":""},{"old":"/api/admin/projects/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_projects.update']['types'],
  },
  'admin_projects.destroy': {
    methods: ["DELETE"],
    pattern: '/api/admin/projects/:id',
    tokens: [{"old":"/api/admin/projects/:id","type":0,"val":"api","end":""},{"old":"/api/admin/projects/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/projects/:id","type":0,"val":"projects","end":""},{"old":"/api/admin/projects/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_projects.destroy']['types'],
  },
  'admin_project_categories.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/project-categories',
    tokens: [{"old":"/api/admin/project-categories","type":0,"val":"api","end":""},{"old":"/api/admin/project-categories","type":0,"val":"admin","end":""},{"old":"/api/admin/project-categories","type":0,"val":"project-categories","end":""}],
    types: placeholder as Registry['admin_project_categories.index']['types'],
  },
  'admin_project_categories.store': {
    methods: ["POST"],
    pattern: '/api/admin/project-categories',
    tokens: [{"old":"/api/admin/project-categories","type":0,"val":"api","end":""},{"old":"/api/admin/project-categories","type":0,"val":"admin","end":""},{"old":"/api/admin/project-categories","type":0,"val":"project-categories","end":""}],
    types: placeholder as Registry['admin_project_categories.store']['types'],
  },
  'admin_project_categories.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/project-categories/:id',
    tokens: [{"old":"/api/admin/project-categories/:id","type":0,"val":"api","end":""},{"old":"/api/admin/project-categories/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/project-categories/:id","type":0,"val":"project-categories","end":""},{"old":"/api/admin/project-categories/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_project_categories.show']['types'],
  },
  'admin_project_categories.update': {
    methods: ["PUT"],
    pattern: '/api/admin/project-categories/:id',
    tokens: [{"old":"/api/admin/project-categories/:id","type":0,"val":"api","end":""},{"old":"/api/admin/project-categories/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/project-categories/:id","type":0,"val":"project-categories","end":""},{"old":"/api/admin/project-categories/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_project_categories.update']['types'],
  },
  'admin_project_categories.destroy': {
    methods: ["DELETE"],
    pattern: '/api/admin/project-categories/:id',
    tokens: [{"old":"/api/admin/project-categories/:id","type":0,"val":"api","end":""},{"old":"/api/admin/project-categories/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/project-categories/:id","type":0,"val":"project-categories","end":""},{"old":"/api/admin/project-categories/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_project_categories.destroy']['types'],
  },
  'admin_articles.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/articles',
    tokens: [{"old":"/api/admin/articles","type":0,"val":"api","end":""},{"old":"/api/admin/articles","type":0,"val":"admin","end":""},{"old":"/api/admin/articles","type":0,"val":"articles","end":""}],
    types: placeholder as Registry['admin_articles.index']['types'],
  },
  'admin_articles.store': {
    methods: ["POST"],
    pattern: '/api/admin/articles',
    tokens: [{"old":"/api/admin/articles","type":0,"val":"api","end":""},{"old":"/api/admin/articles","type":0,"val":"admin","end":""},{"old":"/api/admin/articles","type":0,"val":"articles","end":""}],
    types: placeholder as Registry['admin_articles.store']['types'],
  },
  'admin_articles.publish_scheduled': {
    methods: ["POST"],
    pattern: '/api/admin/articles/publish-scheduled',
    tokens: [{"old":"/api/admin/articles/publish-scheduled","type":0,"val":"api","end":""},{"old":"/api/admin/articles/publish-scheduled","type":0,"val":"admin","end":""},{"old":"/api/admin/articles/publish-scheduled","type":0,"val":"articles","end":""},{"old":"/api/admin/articles/publish-scheduled","type":0,"val":"publish-scheduled","end":""}],
    types: placeholder as Registry['admin_articles.publish_scheduled']['types'],
  },
  'admin_articles.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/articles/:id',
    tokens: [{"old":"/api/admin/articles/:id","type":0,"val":"api","end":""},{"old":"/api/admin/articles/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/articles/:id","type":0,"val":"articles","end":""},{"old":"/api/admin/articles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_articles.show']['types'],
  },
  'admin_articles.preview_url': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/articles/:id/preview-url',
    tokens: [{"old":"/api/admin/articles/:id/preview-url","type":0,"val":"api","end":""},{"old":"/api/admin/articles/:id/preview-url","type":0,"val":"admin","end":""},{"old":"/api/admin/articles/:id/preview-url","type":0,"val":"articles","end":""},{"old":"/api/admin/articles/:id/preview-url","type":1,"val":"id","end":""},{"old":"/api/admin/articles/:id/preview-url","type":0,"val":"preview-url","end":""}],
    types: placeholder as Registry['admin_articles.preview_url']['types'],
  },
  'admin_articles.analytics': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/articles/:id/analytics',
    tokens: [{"old":"/api/admin/articles/:id/analytics","type":0,"val":"api","end":""},{"old":"/api/admin/articles/:id/analytics","type":0,"val":"admin","end":""},{"old":"/api/admin/articles/:id/analytics","type":0,"val":"articles","end":""},{"old":"/api/admin/articles/:id/analytics","type":1,"val":"id","end":""},{"old":"/api/admin/articles/:id/analytics","type":0,"val":"analytics","end":""}],
    types: placeholder as Registry['admin_articles.analytics']['types'],
  },
  'admin_articles.update': {
    methods: ["PUT"],
    pattern: '/api/admin/articles/:id',
    tokens: [{"old":"/api/admin/articles/:id","type":0,"val":"api","end":""},{"old":"/api/admin/articles/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/articles/:id","type":0,"val":"articles","end":""},{"old":"/api/admin/articles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_articles.update']['types'],
  },
  'admin_articles.destroy': {
    methods: ["DELETE"],
    pattern: '/api/admin/articles/:id',
    tokens: [{"old":"/api/admin/articles/:id","type":0,"val":"api","end":""},{"old":"/api/admin/articles/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/articles/:id","type":0,"val":"articles","end":""},{"old":"/api/admin/articles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_articles.destroy']['types'],
  },
  'admin_articles.toggle_status': {
    methods: ["PATCH"],
    pattern: '/api/admin/articles/:id/status',
    tokens: [{"old":"/api/admin/articles/:id/status","type":0,"val":"api","end":""},{"old":"/api/admin/articles/:id/status","type":0,"val":"admin","end":""},{"old":"/api/admin/articles/:id/status","type":0,"val":"articles","end":""},{"old":"/api/admin/articles/:id/status","type":1,"val":"id","end":""},{"old":"/api/admin/articles/:id/status","type":0,"val":"status","end":""}],
    types: placeholder as Registry['admin_articles.toggle_status']['types'],
  },
  'admin_categories.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/categories',
    tokens: [{"old":"/api/admin/categories","type":0,"val":"api","end":""},{"old":"/api/admin/categories","type":0,"val":"admin","end":""},{"old":"/api/admin/categories","type":0,"val":"categories","end":""}],
    types: placeholder as Registry['admin_categories.index']['types'],
  },
  'admin_categories.store': {
    methods: ["POST"],
    pattern: '/api/admin/categories',
    tokens: [{"old":"/api/admin/categories","type":0,"val":"api","end":""},{"old":"/api/admin/categories","type":0,"val":"admin","end":""},{"old":"/api/admin/categories","type":0,"val":"categories","end":""}],
    types: placeholder as Registry['admin_categories.store']['types'],
  },
  'admin_categories.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/categories/:id',
    tokens: [{"old":"/api/admin/categories/:id","type":0,"val":"api","end":""},{"old":"/api/admin/categories/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/categories/:id","type":0,"val":"categories","end":""},{"old":"/api/admin/categories/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_categories.show']['types'],
  },
  'admin_categories.update': {
    methods: ["PUT"],
    pattern: '/api/admin/categories/:id',
    tokens: [{"old":"/api/admin/categories/:id","type":0,"val":"api","end":""},{"old":"/api/admin/categories/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/categories/:id","type":0,"val":"categories","end":""},{"old":"/api/admin/categories/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_categories.update']['types'],
  },
  'admin_categories.destroy': {
    methods: ["DELETE"],
    pattern: '/api/admin/categories/:id',
    tokens: [{"old":"/api/admin/categories/:id","type":0,"val":"api","end":""},{"old":"/api/admin/categories/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/categories/:id","type":0,"val":"categories","end":""},{"old":"/api/admin/categories/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_categories.destroy']['types'],
  },
  'admin_tags.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/tags',
    tokens: [{"old":"/api/admin/tags","type":0,"val":"api","end":""},{"old":"/api/admin/tags","type":0,"val":"admin","end":""},{"old":"/api/admin/tags","type":0,"val":"tags","end":""}],
    types: placeholder as Registry['admin_tags.index']['types'],
  },
  'admin_tags.store': {
    methods: ["POST"],
    pattern: '/api/admin/tags',
    tokens: [{"old":"/api/admin/tags","type":0,"val":"api","end":""},{"old":"/api/admin/tags","type":0,"val":"admin","end":""},{"old":"/api/admin/tags","type":0,"val":"tags","end":""}],
    types: placeholder as Registry['admin_tags.store']['types'],
  },
  'admin_tags.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/tags/:id',
    tokens: [{"old":"/api/admin/tags/:id","type":0,"val":"api","end":""},{"old":"/api/admin/tags/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/tags/:id","type":0,"val":"tags","end":""},{"old":"/api/admin/tags/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_tags.show']['types'],
  },
  'admin_tags.update': {
    methods: ["PUT"],
    pattern: '/api/admin/tags/:id',
    tokens: [{"old":"/api/admin/tags/:id","type":0,"val":"api","end":""},{"old":"/api/admin/tags/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/tags/:id","type":0,"val":"tags","end":""},{"old":"/api/admin/tags/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_tags.update']['types'],
  },
  'admin_tags.destroy': {
    methods: ["DELETE"],
    pattern: '/api/admin/tags/:id',
    tokens: [{"old":"/api/admin/tags/:id","type":0,"val":"api","end":""},{"old":"/api/admin/tags/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/tags/:id","type":0,"val":"tags","end":""},{"old":"/api/admin/tags/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_tags.destroy']['types'],
  },
  'admin_tech_stacks.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/tech-stacks',
    tokens: [{"old":"/api/admin/tech-stacks","type":0,"val":"api","end":""},{"old":"/api/admin/tech-stacks","type":0,"val":"admin","end":""},{"old":"/api/admin/tech-stacks","type":0,"val":"tech-stacks","end":""}],
    types: placeholder as Registry['admin_tech_stacks.index']['types'],
  },
  'admin_tech_stacks.store': {
    methods: ["POST"],
    pattern: '/api/admin/tech-stacks',
    tokens: [{"old":"/api/admin/tech-stacks","type":0,"val":"api","end":""},{"old":"/api/admin/tech-stacks","type":0,"val":"admin","end":""},{"old":"/api/admin/tech-stacks","type":0,"val":"tech-stacks","end":""}],
    types: placeholder as Registry['admin_tech_stacks.store']['types'],
  },
  'admin_tech_stacks.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/tech-stacks/:id',
    tokens: [{"old":"/api/admin/tech-stacks/:id","type":0,"val":"api","end":""},{"old":"/api/admin/tech-stacks/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/tech-stacks/:id","type":0,"val":"tech-stacks","end":""},{"old":"/api/admin/tech-stacks/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_tech_stacks.show']['types'],
  },
  'admin_tech_stacks.update': {
    methods: ["PUT"],
    pattern: '/api/admin/tech-stacks/:id',
    tokens: [{"old":"/api/admin/tech-stacks/:id","type":0,"val":"api","end":""},{"old":"/api/admin/tech-stacks/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/tech-stacks/:id","type":0,"val":"tech-stacks","end":""},{"old":"/api/admin/tech-stacks/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_tech_stacks.update']['types'],
  },
  'admin_tech_stacks.destroy': {
    methods: ["DELETE"],
    pattern: '/api/admin/tech-stacks/:id',
    tokens: [{"old":"/api/admin/tech-stacks/:id","type":0,"val":"api","end":""},{"old":"/api/admin/tech-stacks/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/tech-stacks/:id","type":0,"val":"tech-stacks","end":""},{"old":"/api/admin/tech-stacks/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_tech_stacks.destroy']['types'],
  },
  'admin_experiences.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/experiences',
    tokens: [{"old":"/api/admin/experiences","type":0,"val":"api","end":""},{"old":"/api/admin/experiences","type":0,"val":"admin","end":""},{"old":"/api/admin/experiences","type":0,"val":"experiences","end":""}],
    types: placeholder as Registry['admin_experiences.index']['types'],
  },
  'admin_experiences.store': {
    methods: ["POST"],
    pattern: '/api/admin/experiences',
    tokens: [{"old":"/api/admin/experiences","type":0,"val":"api","end":""},{"old":"/api/admin/experiences","type":0,"val":"admin","end":""},{"old":"/api/admin/experiences","type":0,"val":"experiences","end":""}],
    types: placeholder as Registry['admin_experiences.store']['types'],
  },
  'admin_experiences.reorder': {
    methods: ["POST"],
    pattern: '/api/admin/experiences/reorder',
    tokens: [{"old":"/api/admin/experiences/reorder","type":0,"val":"api","end":""},{"old":"/api/admin/experiences/reorder","type":0,"val":"admin","end":""},{"old":"/api/admin/experiences/reorder","type":0,"val":"experiences","end":""},{"old":"/api/admin/experiences/reorder","type":0,"val":"reorder","end":""}],
    types: placeholder as Registry['admin_experiences.reorder']['types'],
  },
  'admin_experiences.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/experiences/:id',
    tokens: [{"old":"/api/admin/experiences/:id","type":0,"val":"api","end":""},{"old":"/api/admin/experiences/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/experiences/:id","type":0,"val":"experiences","end":""},{"old":"/api/admin/experiences/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_experiences.show']['types'],
  },
  'admin_experiences.update': {
    methods: ["PUT"],
    pattern: '/api/admin/experiences/:id',
    tokens: [{"old":"/api/admin/experiences/:id","type":0,"val":"api","end":""},{"old":"/api/admin/experiences/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/experiences/:id","type":0,"val":"experiences","end":""},{"old":"/api/admin/experiences/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_experiences.update']['types'],
  },
  'admin_experiences.destroy': {
    methods: ["DELETE"],
    pattern: '/api/admin/experiences/:id',
    tokens: [{"old":"/api/admin/experiences/:id","type":0,"val":"api","end":""},{"old":"/api/admin/experiences/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/experiences/:id","type":0,"val":"experiences","end":""},{"old":"/api/admin/experiences/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_experiences.destroy']['types'],
  },
  'admin_educations.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/educations',
    tokens: [{"old":"/api/admin/educations","type":0,"val":"api","end":""},{"old":"/api/admin/educations","type":0,"val":"admin","end":""},{"old":"/api/admin/educations","type":0,"val":"educations","end":""}],
    types: placeholder as Registry['admin_educations.index']['types'],
  },
  'admin_educations.store': {
    methods: ["POST"],
    pattern: '/api/admin/educations',
    tokens: [{"old":"/api/admin/educations","type":0,"val":"api","end":""},{"old":"/api/admin/educations","type":0,"val":"admin","end":""},{"old":"/api/admin/educations","type":0,"val":"educations","end":""}],
    types: placeholder as Registry['admin_educations.store']['types'],
  },
  'admin_educations.reorder': {
    methods: ["POST"],
    pattern: '/api/admin/educations/reorder',
    tokens: [{"old":"/api/admin/educations/reorder","type":0,"val":"api","end":""},{"old":"/api/admin/educations/reorder","type":0,"val":"admin","end":""},{"old":"/api/admin/educations/reorder","type":0,"val":"educations","end":""},{"old":"/api/admin/educations/reorder","type":0,"val":"reorder","end":""}],
    types: placeholder as Registry['admin_educations.reorder']['types'],
  },
  'admin_educations.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/educations/:id',
    tokens: [{"old":"/api/admin/educations/:id","type":0,"val":"api","end":""},{"old":"/api/admin/educations/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/educations/:id","type":0,"val":"educations","end":""},{"old":"/api/admin/educations/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_educations.show']['types'],
  },
  'admin_educations.update': {
    methods: ["PUT"],
    pattern: '/api/admin/educations/:id',
    tokens: [{"old":"/api/admin/educations/:id","type":0,"val":"api","end":""},{"old":"/api/admin/educations/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/educations/:id","type":0,"val":"educations","end":""},{"old":"/api/admin/educations/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_educations.update']['types'],
  },
  'admin_educations.destroy': {
    methods: ["DELETE"],
    pattern: '/api/admin/educations/:id',
    tokens: [{"old":"/api/admin/educations/:id","type":0,"val":"api","end":""},{"old":"/api/admin/educations/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/educations/:id","type":0,"val":"educations","end":""},{"old":"/api/admin/educations/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_educations.destroy']['types'],
  },
  'admin_certifications.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/certifications',
    tokens: [{"old":"/api/admin/certifications","type":0,"val":"api","end":""},{"old":"/api/admin/certifications","type":0,"val":"admin","end":""},{"old":"/api/admin/certifications","type":0,"val":"certifications","end":""}],
    types: placeholder as Registry['admin_certifications.index']['types'],
  },
  'admin_certifications.store': {
    methods: ["POST"],
    pattern: '/api/admin/certifications',
    tokens: [{"old":"/api/admin/certifications","type":0,"val":"api","end":""},{"old":"/api/admin/certifications","type":0,"val":"admin","end":""},{"old":"/api/admin/certifications","type":0,"val":"certifications","end":""}],
    types: placeholder as Registry['admin_certifications.store']['types'],
  },
  'admin_certifications.reorder': {
    methods: ["POST"],
    pattern: '/api/admin/certifications/reorder',
    tokens: [{"old":"/api/admin/certifications/reorder","type":0,"val":"api","end":""},{"old":"/api/admin/certifications/reorder","type":0,"val":"admin","end":""},{"old":"/api/admin/certifications/reorder","type":0,"val":"certifications","end":""},{"old":"/api/admin/certifications/reorder","type":0,"val":"reorder","end":""}],
    types: placeholder as Registry['admin_certifications.reorder']['types'],
  },
  'admin_certifications.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/certifications/:id',
    tokens: [{"old":"/api/admin/certifications/:id","type":0,"val":"api","end":""},{"old":"/api/admin/certifications/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/certifications/:id","type":0,"val":"certifications","end":""},{"old":"/api/admin/certifications/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_certifications.show']['types'],
  },
  'admin_certifications.update': {
    methods: ["PUT"],
    pattern: '/api/admin/certifications/:id',
    tokens: [{"old":"/api/admin/certifications/:id","type":0,"val":"api","end":""},{"old":"/api/admin/certifications/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/certifications/:id","type":0,"val":"certifications","end":""},{"old":"/api/admin/certifications/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_certifications.update']['types'],
  },
  'admin_certifications.destroy': {
    methods: ["DELETE"],
    pattern: '/api/admin/certifications/:id',
    tokens: [{"old":"/api/admin/certifications/:id","type":0,"val":"api","end":""},{"old":"/api/admin/certifications/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/certifications/:id","type":0,"val":"certifications","end":""},{"old":"/api/admin/certifications/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_certifications.destroy']['types'],
  },
  'admin_services.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/services',
    tokens: [{"old":"/api/admin/services","type":0,"val":"api","end":""},{"old":"/api/admin/services","type":0,"val":"admin","end":""},{"old":"/api/admin/services","type":0,"val":"services","end":""}],
    types: placeholder as Registry['admin_services.index']['types'],
  },
  'admin_services.store': {
    methods: ["POST"],
    pattern: '/api/admin/services',
    tokens: [{"old":"/api/admin/services","type":0,"val":"api","end":""},{"old":"/api/admin/services","type":0,"val":"admin","end":""},{"old":"/api/admin/services","type":0,"val":"services","end":""}],
    types: placeholder as Registry['admin_services.store']['types'],
  },
  'admin_services.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/services/:id',
    tokens: [{"old":"/api/admin/services/:id","type":0,"val":"api","end":""},{"old":"/api/admin/services/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/services/:id","type":0,"val":"services","end":""},{"old":"/api/admin/services/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_services.show']['types'],
  },
  'admin_services.update': {
    methods: ["PUT"],
    pattern: '/api/admin/services/:id',
    tokens: [{"old":"/api/admin/services/:id","type":0,"val":"api","end":""},{"old":"/api/admin/services/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/services/:id","type":0,"val":"services","end":""},{"old":"/api/admin/services/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_services.update']['types'],
  },
  'admin_services.destroy': {
    methods: ["DELETE"],
    pattern: '/api/admin/services/:id',
    tokens: [{"old":"/api/admin/services/:id","type":0,"val":"api","end":""},{"old":"/api/admin/services/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/services/:id","type":0,"val":"services","end":""},{"old":"/api/admin/services/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_services.destroy']['types'],
  },
  'admin_philosophies.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/philosophies',
    tokens: [{"old":"/api/admin/philosophies","type":0,"val":"api","end":""},{"old":"/api/admin/philosophies","type":0,"val":"admin","end":""},{"old":"/api/admin/philosophies","type":0,"val":"philosophies","end":""}],
    types: placeholder as Registry['admin_philosophies.index']['types'],
  },
  'admin_philosophies.store': {
    methods: ["POST"],
    pattern: '/api/admin/philosophies',
    tokens: [{"old":"/api/admin/philosophies","type":0,"val":"api","end":""},{"old":"/api/admin/philosophies","type":0,"val":"admin","end":""},{"old":"/api/admin/philosophies","type":0,"val":"philosophies","end":""}],
    types: placeholder as Registry['admin_philosophies.store']['types'],
  },
  'admin_philosophies.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/philosophies/:id',
    tokens: [{"old":"/api/admin/philosophies/:id","type":0,"val":"api","end":""},{"old":"/api/admin/philosophies/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/philosophies/:id","type":0,"val":"philosophies","end":""},{"old":"/api/admin/philosophies/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_philosophies.show']['types'],
  },
  'admin_philosophies.update': {
    methods: ["PUT"],
    pattern: '/api/admin/philosophies/:id',
    tokens: [{"old":"/api/admin/philosophies/:id","type":0,"val":"api","end":""},{"old":"/api/admin/philosophies/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/philosophies/:id","type":0,"val":"philosophies","end":""},{"old":"/api/admin/philosophies/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_philosophies.update']['types'],
  },
  'admin_philosophies.destroy': {
    methods: ["DELETE"],
    pattern: '/api/admin/philosophies/:id',
    tokens: [{"old":"/api/admin/philosophies/:id","type":0,"val":"api","end":""},{"old":"/api/admin/philosophies/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/philosophies/:id","type":0,"val":"philosophies","end":""},{"old":"/api/admin/philosophies/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_philosophies.destroy']['types'],
  },
  'admin_workflows.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/workflows',
    tokens: [{"old":"/api/admin/workflows","type":0,"val":"api","end":""},{"old":"/api/admin/workflows","type":0,"val":"admin","end":""},{"old":"/api/admin/workflows","type":0,"val":"workflows","end":""}],
    types: placeholder as Registry['admin_workflows.index']['types'],
  },
  'admin_workflows.store': {
    methods: ["POST"],
    pattern: '/api/admin/workflows',
    tokens: [{"old":"/api/admin/workflows","type":0,"val":"api","end":""},{"old":"/api/admin/workflows","type":0,"val":"admin","end":""},{"old":"/api/admin/workflows","type":0,"val":"workflows","end":""}],
    types: placeholder as Registry['admin_workflows.store']['types'],
  },
  'admin_workflows.reorder': {
    methods: ["POST"],
    pattern: '/api/admin/workflows/reorder',
    tokens: [{"old":"/api/admin/workflows/reorder","type":0,"val":"api","end":""},{"old":"/api/admin/workflows/reorder","type":0,"val":"admin","end":""},{"old":"/api/admin/workflows/reorder","type":0,"val":"workflows","end":""},{"old":"/api/admin/workflows/reorder","type":0,"val":"reorder","end":""}],
    types: placeholder as Registry['admin_workflows.reorder']['types'],
  },
  'admin_workflows.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/workflows/:id',
    tokens: [{"old":"/api/admin/workflows/:id","type":0,"val":"api","end":""},{"old":"/api/admin/workflows/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/workflows/:id","type":0,"val":"workflows","end":""},{"old":"/api/admin/workflows/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_workflows.show']['types'],
  },
  'admin_workflows.update': {
    methods: ["PUT"],
    pattern: '/api/admin/workflows/:id',
    tokens: [{"old":"/api/admin/workflows/:id","type":0,"val":"api","end":""},{"old":"/api/admin/workflows/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/workflows/:id","type":0,"val":"workflows","end":""},{"old":"/api/admin/workflows/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_workflows.update']['types'],
  },
  'admin_workflows.destroy': {
    methods: ["DELETE"],
    pattern: '/api/admin/workflows/:id',
    tokens: [{"old":"/api/admin/workflows/:id","type":0,"val":"api","end":""},{"old":"/api/admin/workflows/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/workflows/:id","type":0,"val":"workflows","end":""},{"old":"/api/admin/workflows/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_workflows.destroy']['types'],
  },
  'admin_expertises.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/expertises',
    tokens: [{"old":"/api/admin/expertises","type":0,"val":"api","end":""},{"old":"/api/admin/expertises","type":0,"val":"admin","end":""},{"old":"/api/admin/expertises","type":0,"val":"expertises","end":""}],
    types: placeholder as Registry['admin_expertises.index']['types'],
  },
  'admin_expertises.store': {
    methods: ["POST"],
    pattern: '/api/admin/expertises',
    tokens: [{"old":"/api/admin/expertises","type":0,"val":"api","end":""},{"old":"/api/admin/expertises","type":0,"val":"admin","end":""},{"old":"/api/admin/expertises","type":0,"val":"expertises","end":""}],
    types: placeholder as Registry['admin_expertises.store']['types'],
  },
  'admin_expertises.reorder': {
    methods: ["POST"],
    pattern: '/api/admin/expertises/reorder',
    tokens: [{"old":"/api/admin/expertises/reorder","type":0,"val":"api","end":""},{"old":"/api/admin/expertises/reorder","type":0,"val":"admin","end":""},{"old":"/api/admin/expertises/reorder","type":0,"val":"expertises","end":""},{"old":"/api/admin/expertises/reorder","type":0,"val":"reorder","end":""}],
    types: placeholder as Registry['admin_expertises.reorder']['types'],
  },
  'admin_expertises.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/expertises/:id',
    tokens: [{"old":"/api/admin/expertises/:id","type":0,"val":"api","end":""},{"old":"/api/admin/expertises/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/expertises/:id","type":0,"val":"expertises","end":""},{"old":"/api/admin/expertises/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_expertises.show']['types'],
  },
  'admin_expertises.update': {
    methods: ["PUT"],
    pattern: '/api/admin/expertises/:id',
    tokens: [{"old":"/api/admin/expertises/:id","type":0,"val":"api","end":""},{"old":"/api/admin/expertises/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/expertises/:id","type":0,"val":"expertises","end":""},{"old":"/api/admin/expertises/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_expertises.update']['types'],
  },
  'admin_expertises.destroy': {
    methods: ["DELETE"],
    pattern: '/api/admin/expertises/:id',
    tokens: [{"old":"/api/admin/expertises/:id","type":0,"val":"api","end":""},{"old":"/api/admin/expertises/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/expertises/:id","type":0,"val":"expertises","end":""},{"old":"/api/admin/expertises/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_expertises.destroy']['types'],
  },
  'admin_inboxes.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/inboxes',
    tokens: [{"old":"/api/admin/inboxes","type":0,"val":"api","end":""},{"old":"/api/admin/inboxes","type":0,"val":"admin","end":""},{"old":"/api/admin/inboxes","type":0,"val":"inboxes","end":""}],
    types: placeholder as Registry['admin_inboxes.index']['types'],
  },
  'admin_inboxes.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/inboxes/:id',
    tokens: [{"old":"/api/admin/inboxes/:id","type":0,"val":"api","end":""},{"old":"/api/admin/inboxes/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/inboxes/:id","type":0,"val":"inboxes","end":""},{"old":"/api/admin/inboxes/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_inboxes.show']['types'],
  },
  'admin_inboxes.update_status': {
    methods: ["PATCH"],
    pattern: '/api/admin/inboxes/:id/status',
    tokens: [{"old":"/api/admin/inboxes/:id/status","type":0,"val":"api","end":""},{"old":"/api/admin/inboxes/:id/status","type":0,"val":"admin","end":""},{"old":"/api/admin/inboxes/:id/status","type":0,"val":"inboxes","end":""},{"old":"/api/admin/inboxes/:id/status","type":1,"val":"id","end":""},{"old":"/api/admin/inboxes/:id/status","type":0,"val":"status","end":""}],
    types: placeholder as Registry['admin_inboxes.update_status']['types'],
  },
  'admin_inboxes.destroy': {
    methods: ["DELETE"],
    pattern: '/api/admin/inboxes/:id',
    tokens: [{"old":"/api/admin/inboxes/:id","type":0,"val":"api","end":""},{"old":"/api/admin/inboxes/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/inboxes/:id","type":0,"val":"inboxes","end":""},{"old":"/api/admin/inboxes/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_inboxes.destroy']['types'],
  },
  'admin_media.stats': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/media/stats',
    tokens: [{"old":"/api/admin/media/stats","type":0,"val":"api","end":""},{"old":"/api/admin/media/stats","type":0,"val":"admin","end":""},{"old":"/api/admin/media/stats","type":0,"val":"media","end":""},{"old":"/api/admin/media/stats","type":0,"val":"stats","end":""}],
    types: placeholder as Registry['admin_media.stats']['types'],
  },
  'admin_media.bulk_destroy': {
    methods: ["POST"],
    pattern: '/api/admin/media/bulk-delete',
    tokens: [{"old":"/api/admin/media/bulk-delete","type":0,"val":"api","end":""},{"old":"/api/admin/media/bulk-delete","type":0,"val":"admin","end":""},{"old":"/api/admin/media/bulk-delete","type":0,"val":"media","end":""},{"old":"/api/admin/media/bulk-delete","type":0,"val":"bulk-delete","end":""}],
    types: placeholder as Registry['admin_media.bulk_destroy']['types'],
  },
  'admin_media.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/media',
    tokens: [{"old":"/api/admin/media","type":0,"val":"api","end":""},{"old":"/api/admin/media","type":0,"val":"admin","end":""},{"old":"/api/admin/media","type":0,"val":"media","end":""}],
    types: placeholder as Registry['admin_media.index']['types'],
  },
  'admin_media.upload': {
    methods: ["POST"],
    pattern: '/api/admin/media/upload',
    tokens: [{"old":"/api/admin/media/upload","type":0,"val":"api","end":""},{"old":"/api/admin/media/upload","type":0,"val":"admin","end":""},{"old":"/api/admin/media/upload","type":0,"val":"media","end":""},{"old":"/api/admin/media/upload","type":0,"val":"upload","end":""}],
    types: placeholder as Registry['admin_media.upload']['types'],
  },
  'admin_media.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/media/:id',
    tokens: [{"old":"/api/admin/media/:id","type":0,"val":"api","end":""},{"old":"/api/admin/media/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/media/:id","type":0,"val":"media","end":""},{"old":"/api/admin/media/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_media.show']['types'],
  },
  'admin_media.update': {
    methods: ["PATCH"],
    pattern: '/api/admin/media/:id',
    tokens: [{"old":"/api/admin/media/:id","type":0,"val":"api","end":""},{"old":"/api/admin/media/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/media/:id","type":0,"val":"media","end":""},{"old":"/api/admin/media/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_media.update']['types'],
  },
  'admin_media.destroy': {
    methods: ["DELETE"],
    pattern: '/api/admin/media/:id',
    tokens: [{"old":"/api/admin/media/:id","type":0,"val":"api","end":""},{"old":"/api/admin/media/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/media/:id","type":0,"val":"media","end":""},{"old":"/api/admin/media/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_media.destroy']['types'],
  },
  'admin_settings.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/settings',
    tokens: [{"old":"/api/admin/settings","type":0,"val":"api","end":""},{"old":"/api/admin/settings","type":0,"val":"admin","end":""},{"old":"/api/admin/settings","type":0,"val":"settings","end":""}],
    types: placeholder as Registry['admin_settings.index']['types'],
  },
  'admin_settings.update_single': {
    methods: ["PUT"],
    pattern: '/api/admin/settings/single',
    tokens: [{"old":"/api/admin/settings/single","type":0,"val":"api","end":""},{"old":"/api/admin/settings/single","type":0,"val":"admin","end":""},{"old":"/api/admin/settings/single","type":0,"val":"settings","end":""},{"old":"/api/admin/settings/single","type":0,"val":"single","end":""}],
    types: placeholder as Registry['admin_settings.update_single']['types'],
  },
  'admin_settings.update_bulk': {
    methods: ["PUT"],
    pattern: '/api/admin/settings/bulk',
    tokens: [{"old":"/api/admin/settings/bulk","type":0,"val":"api","end":""},{"old":"/api/admin/settings/bulk","type":0,"val":"admin","end":""},{"old":"/api/admin/settings/bulk","type":0,"val":"settings","end":""},{"old":"/api/admin/settings/bulk","type":0,"val":"bulk","end":""}],
    types: placeholder as Registry['admin_settings.update_bulk']['types'],
  },
  'admin_settings.test_telegram': {
    methods: ["POST"],
    pattern: '/api/admin/settings/telegram/test',
    tokens: [{"old":"/api/admin/settings/telegram/test","type":0,"val":"api","end":""},{"old":"/api/admin/settings/telegram/test","type":0,"val":"admin","end":""},{"old":"/api/admin/settings/telegram/test","type":0,"val":"settings","end":""},{"old":"/api/admin/settings/telegram/test","type":0,"val":"telegram","end":""},{"old":"/api/admin/settings/telegram/test","type":0,"val":"test","end":""}],
    types: placeholder as Registry['admin_settings.test_telegram']['types'],
  },
  'admin_activity_logs.stats': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/activity-logs/stats',
    tokens: [{"old":"/api/admin/activity-logs/stats","type":0,"val":"api","end":""},{"old":"/api/admin/activity-logs/stats","type":0,"val":"admin","end":""},{"old":"/api/admin/activity-logs/stats","type":0,"val":"activity-logs","end":""},{"old":"/api/admin/activity-logs/stats","type":0,"val":"stats","end":""}],
    types: placeholder as Registry['admin_activity_logs.stats']['types'],
  },
  'admin_activity_logs.export_logs': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/activity-logs/export',
    tokens: [{"old":"/api/admin/activity-logs/export","type":0,"val":"api","end":""},{"old":"/api/admin/activity-logs/export","type":0,"val":"admin","end":""},{"old":"/api/admin/activity-logs/export","type":0,"val":"activity-logs","end":""},{"old":"/api/admin/activity-logs/export","type":0,"val":"export","end":""}],
    types: placeholder as Registry['admin_activity_logs.export_logs']['types'],
  },
  'admin_activity_logs.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/activity-logs',
    tokens: [{"old":"/api/admin/activity-logs","type":0,"val":"api","end":""},{"old":"/api/admin/activity-logs","type":0,"val":"admin","end":""},{"old":"/api/admin/activity-logs","type":0,"val":"activity-logs","end":""}],
    types: placeholder as Registry['admin_activity_logs.index']['types'],
  },
  'admin_security.get_passkeys': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/security/passkeys',
    tokens: [{"old":"/api/admin/security/passkeys","type":0,"val":"api","end":""},{"old":"/api/admin/security/passkeys","type":0,"val":"admin","end":""},{"old":"/api/admin/security/passkeys","type":0,"val":"security","end":""},{"old":"/api/admin/security/passkeys","type":0,"val":"passkeys","end":""}],
    types: placeholder as Registry['admin_security.get_passkeys']['types'],
  },
  'admin_security.delete_passkey': {
    methods: ["DELETE"],
    pattern: '/api/admin/security/passkeys/:id',
    tokens: [{"old":"/api/admin/security/passkeys/:id","type":0,"val":"api","end":""},{"old":"/api/admin/security/passkeys/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/security/passkeys/:id","type":0,"val":"security","end":""},{"old":"/api/admin/security/passkeys/:id","type":0,"val":"passkeys","end":""},{"old":"/api/admin/security/passkeys/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_security.delete_passkey']['types'],
  },
  'admin_security.get_sessions': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/security/sessions',
    tokens: [{"old":"/api/admin/security/sessions","type":0,"val":"api","end":""},{"old":"/api/admin/security/sessions","type":0,"val":"admin","end":""},{"old":"/api/admin/security/sessions","type":0,"val":"security","end":""},{"old":"/api/admin/security/sessions","type":0,"val":"sessions","end":""}],
    types: placeholder as Registry['admin_security.get_sessions']['types'],
  },
  'admin_security.revoke_session': {
    methods: ["DELETE"],
    pattern: '/api/admin/security/sessions/:id',
    tokens: [{"old":"/api/admin/security/sessions/:id","type":0,"val":"api","end":""},{"old":"/api/admin/security/sessions/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/security/sessions/:id","type":0,"val":"security","end":""},{"old":"/api/admin/security/sessions/:id","type":0,"val":"sessions","end":""},{"old":"/api/admin/security/sessions/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_security.revoke_session']['types'],
  },
  'admin_security.revoke_other_sessions': {
    methods: ["POST"],
    pattern: '/api/admin/security/sessions/revoke-others',
    tokens: [{"old":"/api/admin/security/sessions/revoke-others","type":0,"val":"api","end":""},{"old":"/api/admin/security/sessions/revoke-others","type":0,"val":"admin","end":""},{"old":"/api/admin/security/sessions/revoke-others","type":0,"val":"security","end":""},{"old":"/api/admin/security/sessions/revoke-others","type":0,"val":"sessions","end":""},{"old":"/api/admin/security/sessions/revoke-others","type":0,"val":"revoke-others","end":""}],
    types: placeholder as Registry['admin_security.revoke_other_sessions']['types'],
  },
  'admin_security.update_password': {
    methods: ["PUT"],
    pattern: '/api/admin/security/password',
    tokens: [{"old":"/api/admin/security/password","type":0,"val":"api","end":""},{"old":"/api/admin/security/password","type":0,"val":"admin","end":""},{"old":"/api/admin/security/password","type":0,"val":"security","end":""},{"old":"/api/admin/security/password","type":0,"val":"password","end":""}],
    types: placeholder as Registry['admin_security.update_password']['types'],
  },
  'public_projects.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/projects',
    tokens: [{"old":"/api/v1/projects","type":0,"val":"api","end":""},{"old":"/api/v1/projects","type":0,"val":"v1","end":""},{"old":"/api/v1/projects","type":0,"val":"projects","end":""}],
    types: placeholder as Registry['public_projects.index']['types'],
  },
  'public_projects.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/projects/:slug',
    tokens: [{"old":"/api/v1/projects/:slug","type":0,"val":"api","end":""},{"old":"/api/v1/projects/:slug","type":0,"val":"v1","end":""},{"old":"/api/v1/projects/:slug","type":0,"val":"projects","end":""},{"old":"/api/v1/projects/:slug","type":1,"val":"slug","end":""}],
    types: placeholder as Registry['public_projects.show']['types'],
  },
  'public_projects.track_event': {
    methods: ["POST"],
    pattern: '/api/v1/projects/:slug/track',
    tokens: [{"old":"/api/v1/projects/:slug/track","type":0,"val":"api","end":""},{"old":"/api/v1/projects/:slug/track","type":0,"val":"v1","end":""},{"old":"/api/v1/projects/:slug/track","type":0,"val":"projects","end":""},{"old":"/api/v1/projects/:slug/track","type":1,"val":"slug","end":""},{"old":"/api/v1/projects/:slug/track","type":0,"val":"track","end":""}],
    types: placeholder as Registry['public_projects.track_event']['types'],
  },
  'public.project_categories.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/project-categories',
    tokens: [{"old":"/api/v1/project-categories","type":0,"val":"api","end":""},{"old":"/api/v1/project-categories","type":0,"val":"v1","end":""},{"old":"/api/v1/project-categories","type":0,"val":"project-categories","end":""}],
    types: placeholder as Registry['public.project_categories.index']['types'],
  },
  'public.posts.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/posts',
    tokens: [{"old":"/api/v1/posts","type":0,"val":"api","end":""},{"old":"/api/v1/posts","type":0,"val":"v1","end":""},{"old":"/api/v1/posts","type":0,"val":"posts","end":""}],
    types: placeholder as Registry['public.posts.index']['types'],
  },
  'public.posts.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/posts/:slug',
    tokens: [{"old":"/api/v1/posts/:slug","type":0,"val":"api","end":""},{"old":"/api/v1/posts/:slug","type":0,"val":"v1","end":""},{"old":"/api/v1/posts/:slug","type":0,"val":"posts","end":""},{"old":"/api/v1/posts/:slug","type":1,"val":"slug","end":""}],
    types: placeholder as Registry['public.posts.show']['types'],
  },
  'public.articles.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/articles',
    tokens: [{"old":"/api/v1/articles","type":0,"val":"api","end":""},{"old":"/api/v1/articles","type":0,"val":"v1","end":""},{"old":"/api/v1/articles","type":0,"val":"articles","end":""}],
    types: placeholder as Registry['public.articles.index']['types'],
  },
  'public.articles.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/articles/:slug',
    tokens: [{"old":"/api/v1/articles/:slug","type":0,"val":"api","end":""},{"old":"/api/v1/articles/:slug","type":0,"val":"v1","end":""},{"old":"/api/v1/articles/:slug","type":0,"val":"articles","end":""},{"old":"/api/v1/articles/:slug","type":1,"val":"slug","end":""}],
    types: placeholder as Registry['public.articles.show']['types'],
  },
  'public.categories.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/categories',
    tokens: [{"old":"/api/v1/categories","type":0,"val":"api","end":""},{"old":"/api/v1/categories","type":0,"val":"v1","end":""},{"old":"/api/v1/categories","type":0,"val":"categories","end":""}],
    types: placeholder as Registry['public.categories.index']['types'],
  },
  'public.tags.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/tags',
    tokens: [{"old":"/api/v1/tags","type":0,"val":"api","end":""},{"old":"/api/v1/tags","type":0,"val":"v1","end":""},{"old":"/api/v1/tags","type":0,"val":"tags","end":""}],
    types: placeholder as Registry['public.tags.index']['types'],
  },
  'public_tech_stacks.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/tech-stacks',
    tokens: [{"old":"/api/v1/tech-stacks","type":0,"val":"api","end":""},{"old":"/api/v1/tech-stacks","type":0,"val":"v1","end":""},{"old":"/api/v1/tech-stacks","type":0,"val":"tech-stacks","end":""}],
    types: placeholder as Registry['public_tech_stacks.index']['types'],
  },
  'public_experiences.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/experiences',
    tokens: [{"old":"/api/v1/experiences","type":0,"val":"api","end":""},{"old":"/api/v1/experiences","type":0,"val":"v1","end":""},{"old":"/api/v1/experiences","type":0,"val":"experiences","end":""}],
    types: placeholder as Registry['public_experiences.index']['types'],
  },
  'public_services.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/services',
    tokens: [{"old":"/api/v1/services","type":0,"val":"api","end":""},{"old":"/api/v1/services","type":0,"val":"v1","end":""},{"old":"/api/v1/services","type":0,"val":"services","end":""}],
    types: placeholder as Registry['public_services.index']['types'],
  },
  'public_services.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/services/:slug',
    tokens: [{"old":"/api/v1/services/:slug","type":0,"val":"api","end":""},{"old":"/api/v1/services/:slug","type":0,"val":"v1","end":""},{"old":"/api/v1/services/:slug","type":0,"val":"services","end":""},{"old":"/api/v1/services/:slug","type":1,"val":"slug","end":""}],
    types: placeholder as Registry['public_services.show']['types'],
  },
  'public_philosophies.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/philosophies',
    tokens: [{"old":"/api/v1/philosophies","type":0,"val":"api","end":""},{"old":"/api/v1/philosophies","type":0,"val":"v1","end":""},{"old":"/api/v1/philosophies","type":0,"val":"philosophies","end":""}],
    types: placeholder as Registry['public_philosophies.index']['types'],
  },
  'public_workflows.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/workflows',
    tokens: [{"old":"/api/v1/workflows","type":0,"val":"api","end":""},{"old":"/api/v1/workflows","type":0,"val":"v1","end":""},{"old":"/api/v1/workflows","type":0,"val":"workflows","end":""}],
    types: placeholder as Registry['public_workflows.index']['types'],
  },
  'public_expertises.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/expertises',
    tokens: [{"old":"/api/v1/expertises","type":0,"val":"api","end":""},{"old":"/api/v1/expertises","type":0,"val":"v1","end":""},{"old":"/api/v1/expertises","type":0,"val":"expertises","end":""}],
    types: placeholder as Registry['public_expertises.index']['types'],
  },
  'public_settings.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/settings',
    tokens: [{"old":"/api/v1/settings","type":0,"val":"api","end":""},{"old":"/api/v1/settings","type":0,"val":"v1","end":""},{"old":"/api/v1/settings","type":0,"val":"settings","end":""}],
    types: placeholder as Registry['public_settings.index']['types'],
  },
  'public_inboxes.store': {
    methods: ["POST"],
    pattern: '/api/v1/inbox',
    tokens: [{"old":"/api/v1/inbox","type":0,"val":"api","end":""},{"old":"/api/v1/inbox","type":0,"val":"v1","end":""},{"old":"/api/v1/inbox","type":0,"val":"inbox","end":""}],
    types: placeholder as Registry['public_inboxes.store']['types'],
  },
} as const satisfies Record<string, AdonisEndpoint>

export { routes }

export const registry = {
  routes,
  $tree: {} as ApiDefinition,
}

declare module '@tuyau/core/types' {
  export interface UserRegistry {
    routes: typeof routes
    $tree: ApiDefinition
  }
}
