/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class ActivityLogSchema extends BaseModel {
  static $columns = [
    'action',
    'createdAt',
    'entity',
    'entityId',
    'id',
    'ipAddress',
    'payload',
    'userAgent',
    'userId',
  ] as const
  $columns = ActivityLogSchema.$columns
  @column()
  declare action: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare entity: string
  @column()
  declare entityId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ipAddress: string | null
  @column()
  declare payload: any | null
  @column()
  declare userAgent: string | null
  @column()
  declare userId: string | null
}

export class ArticleViewSchema extends BaseModel {
  static $columns = [
    'browser',
    'createdAt',
    'deviceType',
    'id',
    'ipAddress',
    'os',
    'postId',
    'referrer',
    'referrerSource',
    'userAgent',
    'visitorHash',
  ] as const
  $columns = ArticleViewSchema.$columns
  @column()
  declare browser: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare deviceType: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ipAddress: string | null
  @column()
  declare os: string
  @column()
  declare postId: string
  @column()
  declare referrer: string | null
  @column()
  declare referrerSource: string
  @column()
  declare userAgent: string | null
  @column()
  declare visitorHash: string
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = [
    'abilities',
    'createdAt',
    'expiresAt',
    'hash',
    'id',
    'lastUsedAt',
    'name',
    'tokenableId',
    'type',
    'updatedAt',
  ] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CategorySchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'name', 'slug', 'updatedAt'] as const
  $columns = CategorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CertificationSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'credentialId',
    'credentialUrl',
    'expirationDate',
    'id',
    'issueDate',
    'issuer',
    'issuerLogoUrl',
    'name',
    'order',
    'updatedAt',
  ] as const
  $columns = CertificationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare credentialId: string | null
  @column()
  declare credentialUrl: string | null
  @column.date()
  declare expirationDate: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column.date()
  declare issueDate: DateTime
  @column()
  declare issuer: string
  @column()
  declare issuerLogoUrl: string | null
  @column()
  declare name: string
  @column()
  declare order: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ContactInboxSchema extends BaseModel {
  static $columns = [
    'budgetRange',
    'createdAt',
    'email',
    'id',
    'ipAddress',
    'message',
    'name',
    'projectCategory',
    'repliedAt',
    'replyNotes',
    'status',
    'subject',
    'updatedAt',
    'userAgent',
  ] as const
  $columns = ContactInboxSchema.$columns
  @column()
  declare budgetRange: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ipAddress: string | null
  @column()
  declare message: string
  @column()
  declare name: string
  @column()
  declare projectCategory: string | null
  @column.dateTime()
  declare repliedAt: DateTime | null
  @column()
  declare replyNotes: string | null
  @column()
  declare status: string
  @column()
  declare subject: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userAgent: string | null
}

export class EducationSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'degree',
    'description',
    'endDate',
    'fieldOfStudy',
    'grade',
    'id',
    'institution',
    'institutionLogoUrl',
    'isCurrent',
    'order',
    'startDate',
    'updatedAt',
  ] as const
  $columns = EducationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare degree: string
  @column()
  declare description: string | null
  @column.date()
  declare endDate: DateTime | null
  @column()
  declare fieldOfStudy: string
  @column()
  declare grade: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare institution: string
  @column()
  declare institutionLogoUrl: string | null
  @column()
  declare isCurrent: boolean
  @column()
  declare order: number
  @column.date()
  declare startDate: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ExperienceTechStackSchema extends BaseModel {
  static $columns = ['experienceId', 'id', 'techStackId'] as const
  $columns = ExperienceTechStackSchema.$columns
  @column()
  declare experienceId: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare techStackId: string
}

export class ExperienceSchema extends BaseModel {
  static $columns = [
    'company',
    'companyLogoUrl',
    'createdAt',
    'description',
    'employmentType',
    'endDate',
    'id',
    'isCurrent',
    'location',
    'order',
    'position',
    'startDate',
    'updatedAt',
  ] as const
  $columns = ExperienceSchema.$columns
  @column()
  declare company: string
  @column()
  declare companyLogoUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column()
  declare employmentType: string | null
  @column.date()
  declare endDate: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isCurrent: boolean
  @column()
  declare location: string | null
  @column()
  declare order: number
  @column()
  declare position: string
  @column.date()
  declare startDate: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ExpertiseTechStackSchema extends BaseModel {
  static $columns = ['expertiseId', 'id', 'techStackId'] as const
  $columns = ExpertiseTechStackSchema.$columns
  @column()
  declare expertiseId: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare techStackId: string
}

export class ExpertiseSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'description',
    'iconSvg',
    'id',
    'isFeatured',
    'order',
    'slug',
    'subtitle',
    'title',
    'updatedAt',
  ] as const
  $columns = ExpertiseSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column()
  declare iconSvg: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isFeatured: boolean
  @column()
  declare order: number
  @column()
  declare slug: string
  @column()
  declare subtitle: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MediaAssetSchema extends BaseModel {
  static $columns = [
    'altText',
    'createdAt',
    'fileName',
    'filePath',
    'fileSize',
    'fileUrl',
    'height',
    'id',
    'mediaType',
    'mimeType',
    'updatedAt',
    'width',
  ] as const
  $columns = MediaAssetSchema.$columns
  @column()
  declare altText: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare fileName: string
  @column()
  declare filePath: string
  @column()
  declare fileSize: bigint | number
  @column()
  declare fileUrl: string
  @column()
  declare height: number | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare mediaType: string
  @column()
  declare mimeType: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare width: number | null
}

export class PhilosophySchema extends BaseModel {
  static $columns = [
    'createdAt',
    'description',
    'iconSvg',
    'id',
    'order',
    'tagline',
    'title',
    'updatedAt',
  ] as const
  $columns = PhilosophySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column()
  declare iconSvg: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare order: number
  @column()
  declare tagline: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PostTagSchema extends BaseModel {
  static $columns = ['id', 'postId', 'tagId'] as const
  $columns = PostTagSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare postId: string
  @column()
  declare tagId: string
}

export class PostSchema extends BaseModel {
  static $columns = [
    'categoryId',
    'content',
    'coverImage',
    'createdAt',
    'excerpt',
    'id',
    'metaDescription',
    'metaTitle',
    'publishedAt',
    'readingTimeMinutes',
    'scheduledAt',
    'slug',
    'status',
    'title',
    'updatedAt',
    'viewCount',
  ] as const
  $columns = PostSchema.$columns
  @column()
  declare categoryId: string | null
  @column()
  declare content: string
  @column()
  declare coverImage: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare excerpt: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare metaDescription: string | null
  @column()
  declare metaTitle: string | null
  @column.dateTime()
  declare publishedAt: DateTime | null
  @column()
  declare readingTimeMinutes: number | null
  @column.dateTime()
  declare scheduledAt: DateTime | null
  @column()
  declare slug: string
  @column()
  declare status: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare viewCount: bigint | number
}

export class ProjectCategorySchema extends BaseModel {
  static $columns = [
    'createdAt',
    'description',
    'id',
    'name',
    'order',
    'slug',
    'updatedAt',
  ] as const
  $columns = ProjectCategorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare order: number
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProjectGallerySchema extends BaseModel {
  static $columns = ['caption', 'createdAt', 'id', 'imageUrl', 'projectId', 'sortOrder'] as const
  $columns = ProjectGallerySchema.$columns
  @column()
  declare caption: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare imageUrl: string
  @column()
  declare projectId: string
  @column()
  declare sortOrder: number
}

export class ProjectTechStackSchema extends BaseModel {
  static $columns = ['id', 'projectId', 'techStackId'] as const
  $columns = ProjectTechStackSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare projectId: string
  @column()
  declare techStackId: string
}

export class ProjectViewSchema extends BaseModel {
  static $columns = [
    'browser',
    'createdAt',
    'deviceType',
    'eventType',
    'id',
    'ipAddress',
    'os',
    'projectId',
    'referrer',
    'referrerSource',
    'userAgent',
    'visitorHash',
  ] as const
  $columns = ProjectViewSchema.$columns
  @column()
  declare browser: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare deviceType: string
  @column()
  declare eventType: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ipAddress: string | null
  @column()
  declare os: string
  @column()
  declare projectId: string
  @column()
  declare referrer: string | null
  @column()
  declare referrerSource: string
  @column()
  declare userAgent: string | null
  @column()
  declare visitorHash: string
}

export class ProjectSchema extends BaseModel {
  static $columns = [
    'categoryId',
    'clientName',
    'content',
    'coverImage',
    'createdAt',
    'demoClickCount',
    'demoUrl',
    'excerpt',
    'id',
    'isFeatured',
    'order',
    'projectYear',
    'repoClickCount',
    'repositoryUrl',
    'slug',
    'title',
    'updatedAt',
    'viewCount',
  ] as const
  $columns = ProjectSchema.$columns
  @column()
  declare categoryId: string | null
  @column()
  declare clientName: string | null
  @column()
  declare content: string
  @column()
  declare coverImage: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare demoClickCount: number
  @column()
  declare demoUrl: string | null
  @column()
  declare excerpt: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isFeatured: boolean
  @column()
  declare order: number
  @column()
  declare projectYear: number
  @column()
  declare repoClickCount: number
  @column()
  declare repositoryUrl: string | null
  @column()
  declare slug: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare viewCount: number
}

export class ServiceFaqSchema extends BaseModel {
  static $columns = ['answer', 'createdAt', 'id', 'question', 'serviceId', 'sortOrder'] as const
  $columns = ServiceFaqSchema.$columns
  @column()
  declare answer: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare question: string
  @column()
  declare serviceId: string
  @column()
  declare sortOrder: number
}

export class ServiceSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'deliverables',
    'iconSvg',
    'id',
    'isFeatured',
    'order',
    'shortDescription',
    'slug',
    'title',
    'updatedAt',
    'valueProposition',
  ] as const
  $columns = ServiceSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare deliverables: any
  @column()
  declare iconSvg: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isFeatured: boolean
  @column()
  declare order: number
  @column()
  declare shortDescription: string
  @column()
  declare slug: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare valueProposition: string
}

export class SiteSettingSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'key', 'updatedAt', 'value'] as const
  $columns = SiteSettingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare key: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare value: any
}

export class TagSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'slug', 'updatedAt'] as const
  $columns = TagSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TechStackSchema extends BaseModel {
  static $columns = [
    'category',
    'createdAt',
    'iconSvg',
    'id',
    'isFeatured',
    'level',
    'name',
    'order',
    'slug',
    'updatedAt',
  ] as const
  $columns = TechStackSchema.$columns
  @column()
  declare category: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare iconSvg: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isFeatured: boolean
  @column()
  declare level: number | null
  @column()
  declare name: string
  @column()
  declare order: number
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserPasskeySchema extends BaseModel {
  static $columns = [
    'counter',
    'createdAt',
    'credentialId',
    'deviceName',
    'id',
    'lastUsedAt',
    'publicKey',
    'transports',
    'updatedAt',
    'userId',
  ] as const
  $columns = UserPasskeySchema.$columns
  @column()
  declare counter: bigint | number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare credentialId: string
  @column()
  declare deviceName: string | null
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare publicKey: string
  @column()
  declare transports: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class UserSchema extends BaseModel {
  static $columns = [
    'avatarUrl',
    'createdAt',
    'email',
    'id',
    'name',
    'password',
    'role',
    'updatedAt',
  ] as const
  $columns = UserSchema.$columns
  @column()
  declare avatarUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class WorkflowStepSchema extends BaseModel {
  static $columns = [
    'activities',
    'badgeColor',
    'createdAt',
    'description',
    'iconSvg',
    'id',
    'isActive',
    'order',
    'shortTitle',
    'stepNumber',
    'title',
    'updatedAt',
  ] as const
  $columns = WorkflowStepSchema.$columns
  @column()
  declare activities: any
  @column()
  declare badgeColor: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column()
  declare iconSvg: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column()
  declare order: number
  @column()
  declare shortTitle: string
  @column()
  declare stepNumber: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
